version: '3.8'

services:
  app:
    image: nzkiwikid/honning-inn:latest
    environment:
      - PORT=8080
      - DATABASE_URL=/mnt/volume/data.db
    ports:
      - "8080:8080"
    volumes:
      - sqlite_volume:/mnt/volume
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  sqlite_volume:
